#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Blender -o desktop='^4' focus=on
bspc rule -a "" -o desktop='^5' focus=on
bspc rule -a Firefox -o desktop='^2'  focus=on
bspc rule -a Google-chrome -o desktop='^2' focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill $HOME/Downloads/walls/desk11.jpeg
bspc config focus_follows_pointer true
bspc config border_width 0

xsetroot -cursor_name left_ptr &
picom --experimental-backends &
system76-power profile battery &
$HOME/.config/polybar/launch.sh --colorblocks & 

